In [2]:
import pandas as pd
import numpy as np


In [3]:
#1.读取数据
path = "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data"
column_name = ['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
                   'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
                   'Normal Nucleoli', 'Mitoses', 'Class']
data = pd.read_csv(path,names=column_name)


In [5]:
data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

In [9]:
#2.缺失值处理
#1).替换--》np.nan
data = data.replace(to_replace="?",value=np.nan)
#2).删除缺失样本
data.dropna(inplace=True)

In [11]:
#查看缺失样本是否全部被删除 data.isnull().any() 全都是false表示不存在缺失值了

Sample code number             False
Clump Thickness                False
Uniformity of Cell Size        False
Uniformity of Cell Shape       False
Marginal Adhesion              False
Single Epithelial Cell Size    False
Bare Nuclei                    False
Bland Chromatin                False
Normal Nucleoli                False
Mitoses                        False
Class                          False
dtype: bool

In [12]:
#3.划分数据集
from sklearn.model_selection import train_test_split

In [14]:
#筛选特征值和目标值
x=data.iloc[:, 1:-1]
y=data["Class"]

In [17]:
x

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
0                  5                        1                         1   
1                  5                        4                         4   
2                  3                        1                         1   
3                  6                        8                         8   
4                  4                        1                         1   
..               ...                      ...                       ...   
694                3                        1                         1   
695                2                        1                         1   
696                5                       10                        10   
697                4                        8                         6   
698                4                        8                         8   

     Marginal Adhesion  Single Epithelial Cell Size Bare Nuclei  \
0                    1                            2           1   
1                    5                            7          10   
2                    1                            2           2   
3                    1                            3           4   
4                    3                            2           1   
..                 ...                          ...         ...   
694                  1                            3           2   
695                  1                            2           1   
696                  3                            7           3   
697                  4                            3           4   
698                  5                            4           5   

     Bland Chromatin  Normal Nucleoli  Mitoses  
0                  3                1        1  
1                  3                2        1  
2                  3                1        1  
3                  3                7        1  
4                  3                1        1  
..               ...              ...      ...  
694                1                1        1  
695                1                1        1  
696                8               10        2  
697               10                6        1  
698               10                4        1  

[683 rows x 9 columns]

In [18]:
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [23]:
x_train.head()

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
372                4                        1                         2   
374                3                        1                         2   
684                1                        1                         1   
289                5                        6                         6   
633                8                        7                         4   

     Marginal Adhesion  Single Epithelial Cell Size Bare Nuclei  \
372                  1                            2           1   
374                  1                            2           1   
684                  1                            2           1   
289                  8                            6          10   
633                  4                            5           3   

     Bland Chromatin  Normal Nucleoli  Mitoses  
372                2                1        1  
374                2                1        1  
684                1                1        1  
289                4               10        4  
633                5               10        1

In [24]:
#4.特征工程 标准化
from sklearn.preprocessing import StandardScaler

In [25]:
transfer = StandardScaler()
x_train=transfer.fit_transform(x_train)
x_test=transfer.transform(x_test)

In [26]:
x_train

array([[-0.15158253, -0.70075204, -0.39767837, ..., -0.60607247,
        -0.61275553, -0.35789496],
       [-0.50276016, -0.70075204, -0.39767837, ..., -0.60607247,
        -0.61275553, -0.35789496],
       [-1.20511541, -0.70075204, -0.73478321, ..., -1.00595533,
        -0.61275553, -0.35789496],
       ...,
       [ 1.95548324,  0.5863692 ,  0.61363616, ...,  1.39334185,
         2.32847101, -0.35789496],
       [ 0.1995951 ,  0.5863692 ,  0.61363616, ..., -0.2061896 ,
        -0.61275553, -0.35789496],
       [ 0.1995951 , -0.70075204, -0.73478321, ..., -1.00595533,
        -0.61275553, -0.35789496]])

In [27]:
from sklearn.linear_model import LogisticRegression

In [28]:
#5.预估器流程
estimator = LogisticRegression()
estimator.fit(x_train,y_train)

LogisticRegression()

In [29]:
#6.罗辑回归模型的模型参数:回归系数和偏置
estimator.coef_

array([[1.10733927, 0.12230988, 1.13831353, 1.06480273, 0.3969362 ,
        1.31988774, 0.81809795, 0.69900128, 0.8432489 ]])

In [30]:
estimator.intercept_

array([-0.62460813])

In [31]:
#7.模型评估

y_predict = estimator.predict(x_test) #将测试集的特征值传入，根据先前计算出的模型，来预测所给测试集的目标值】
print("y_predict:\n",y_predict)
print("比较预测值和真实值:\n",y_predict==y_test)

score = estimator.score(x_test,y_test)
print("准确率为:\n",score)

y_predict:
 [4 2 4 2 2 2 4 4 2 2 2 2 2 4 4 2 2 2 4 2 2 4 4 2 2 2 4 4 4 4 2 4 4 4 4 4 4
 4 2 2 2 4 2 2 2 2 2 4 2 2 2 4 4 4 2 2 2 2 2 4 2 2 4 4 2 2 4 2 4 2 4 2 2 4
 2 4 2 4 2 4 4 4 2 2 2 2 2 2 4 4 2 2 4 4 2 2 2 2 2 2 2 2 2 2 2 4 2 2 2 2 2
 2 4 4 4 2 2 2 2 2 4 2 2 2 4 2 2 2 2 2 2 4 2 4 4 4 2 4 2 2 2 4 4 2 2 2 4 2
 2 4 2 2 2 4 2 2 2 4 2 2 4 2 4 4 4 2 2 2 2 2 2]
比较预测值和真实值:
 32     True
194    True
166    True
587    True
331    True
       ... 
645    True
45     True
560    True
163    True
528    True
Name: Class, Length: 171, dtype: bool
准确率为:
 0.9473684210526315


In [32]:
#查看精确率 召回率 以及F1-score
from sklearn.metrics import classification_report

In [33]:
report = classification_report(y_test,y_predict,labels=[2,4],target_names=["良性","恶性"])

In [35]:
print(report)

              precision    recall  f1-score   support

          良性       0.98      0.94      0.96       114
          恶性       0.89      0.96      0.92        57

    accuracy                           0.95       171
   macro avg       0.93      0.95      0.94       171
weighted avg       0.95      0.95      0.95       171



In [36]:
#因为y_true的值必须是0或者1 因此需要将y_test的值转化成2和4
y_true = np.where(y_test > 3,1,0)

In [37]:
y_true

array([1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0])

In [38]:
from sklearn.metrics import roc_auc_score


In [39]:
roc_auc_score(y_true,y_predict)

0.9517543859649122